const express = require('express');
const auth_controller = require('../controllers/auth_controller');
const { PostRequestMiddleware } = require('../middlewares/requests.middleware');
const { AuthenticateMiddleware } = require('../middlewares/authentication.middleware');
const {RegisterSchema, LoginSchema, ChangePasswordSchema} = require('../requests/auth');
const router = express.Router();
router.post('/sign-up' , PostRequestMiddleware(RegisterSchema, 'body'), auth_controller.register_user);
router.post('/sign-in' , PostRequestMiddleware(LoginSchema, 'body'), auth_controller.login);
router.get('/me' , AuthenticateMiddleware(), auth_controller.token_details);
router.put('/change-password' , PostRequestMiddleware(ChangePasswordSchema), auth_controller.change_password);
module.exports = router;
